[custom.layer0]
command = "layer0 profiles list 2>&1 | grep '▸' | awk '{print $2}'"  # shows output of command
symbol = "lØ:"
format = "[$symbol($output) ]($style)"
style = "fg:#991970 italic"
disabled = false
shell = "sh"
when = "true"
